# Generated by Django 5.2.8 on 2026-01-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_alter_member_options_remove_member_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('shop', models.CharField(max_length=200, verbose_name='店名')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('import_month', models.DateField(verbose_name='インポート月')),
                ('is_closed', models.BooleanField(default=False, verbose_name='確定済み')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.category', verbose_name='カテゴリ')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='members.member', verbose_name='使用メンバー')),
            ],
            options={
                'verbose_name': '明細',
                'verbose_name_plural': '明細',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
