# Generated by Django 5.2.8 on 2025-11-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('shop', models.CharField(max_length=100, verbose_name='店名・サービス名')),
                ('amount', models.IntegerField(verbose_name='金額（円）')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='members.member', verbose_name='誰の出費か')),
            ],
            options={
                'verbose_name': '明細',
                'verbose_name_plural': '明細',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
