# Generated by Django 5.2.8 on 2026-01-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options_remove_member_created_at_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='確定済みか'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='members.member', verbose_name='メンバー'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shop',
            field=models.CharField(max_length=255, verbose_name='店名・サービス名'),
        ),
    ]
