# Generated by Django 5.2.8 on 2026-01-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='import_month',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ファイル名'),
        ),
    ]
