# Generated by Django 5.2.8 on 2025-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='decided_by',
            field=models.CharField(choices=[('none', '未判定'), ('rule', 'ルール自動判定'), ('manual', '人間が手動で確定')], default='none', max_length=20, verbose_name='判定方法'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='仕分け確定フラグ'),
        ),
    ]
