# Generated by Django 5.2.8 on 2026-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['id'], 'verbose_name': 'メンバー', 'verbose_name_plural': 'メンバー'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='メンバー名'),
        ),
    ]
